
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../comps/Header';
import { abi } from '../comps/web3/abi/submit.js'
import { useEffect, useState } from 'react';
import Web3 from 'web3';

export default function Home({ p }) {
  // declaration
  const { address, web3 } = p
  const [data, setData] = useState([])
  const [role, setRole] = useState([])
  const [fName, setfName] = useState("")
  const [lName, setlName] = useState("")
  const [userRole, setUserRole] = useState(0)


  // get table data
  const getData = (async () => {
    const web3 = new Web3("https://rinkeby.infura.io/v3/2f85c22a29994320b52da33bec96968d");
    const callContract = new web3.eth.Contract(abi, "0xDfb89f15313Ca9c74Dd6bdaBa3A2306545411f57");
    const totalUser = await callContract.methods.getTotal().call();

    const array = []
    for (let i = 0; i < totalUser; i++) {
      const details = await callContract.methods.USERS(i).call();
      array.push(details)
    }
    setData(array)
    const roles = await callContract.methods.getRoles().call();
    setRole(roles)

  })

  // submit
  const submit = (async () => {
    // check if First Name, Last Name, and Address (if connected address will be true)
    if (fName && lName && address) {
      const callContract = new web3.eth.Contract(abi, "0xDfb89f15313Ca9c74Dd6bdaBa3A2306545411f57");
      const name = `${fName} ${lName}`
      await callContract.methods.addUser(userRole, name).send({ from: address }).then(async function () {
        getData()
      })
    }

  })
  useEffect(() => {
    getData()
  }, [])
  return (
    <>
      <Header p={p} />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            <a href="https://cadena.dev">Cadena.dev</a> Custom dApp
          </h1>

          <p className={styles.description}>
            Put your role here!

          </p>

          <div className='tableForm'>
            <div className="name">
              <input type="text" name="fname" placeholder="Lorem" onChange={(e) => setfName(e.target.value)} />
              <input type="text" name="lname" placeholder="Ipsum" onChange={(e) => setlName(e.target.value)} />
            </div>
            <div className="dropdown">
              <label >Select your Role:</label>
              <select name="select-choice" id="select-choice" onChange={(e) => setUserRole(+e.target.value)}>
                {role.map((item, i) => (
                  <option key={i} value={i} >{role[i]}</option>
                ))}
              </select>
            </div>
            <div className="submit" >
              <button type="submit" style={{ cursor: 'pointer' }} onClick={() => submit()}>Submit</button>
            </div>
          </div>

          <table>
            <tbody>
              <tr>
                <th>Name</th>
                <th>Role</th>
              </tr>

              {data.map((item, i) => (
                <tr key={i}>
                  <td>{item[1]}</td>
                  <td>{item[2]}</td>
                </tr>
              )
              )}


            </tbody>

          </table>

        </main>


      </div>
    </>
  )
}
